### ISSUE TITLE
Moving to a better markdown parser

### ISSUE THREAD

**Issue by aadibajpai** [pastly/bm#8]
Since I'm sticking with bm for my blog needs, I figure might as well do stuff properly.

You're using the OG Markdown parser which, well, is quite outdated. No support for strikethroughs or automatic links or fenced code blocks and stuff.

I'm tempted to wrestle with shell scripts and whatnot to migrate to something more modern such as the github flavored markdown. I'm looking at https://github.com/github/cmark-gfm right now 

My question is, would that be something you're interested in or am I better off just doing it for myself?

**Comment by pastly** [comment]
Adding proper support for a different markdown parser should be straight forward. As a hack I installed the Debian cmark-fgm package, symlinked to it, and rebuilt my blog. Some things rendered differently and it looks like the `{toc}` macro is broken now. But otherwise I think it would not be too hard to make the path to the binary to use configurable. Also, I am open to replacing Markdown.pl in the repo with a cmark-gfm binary as long as things that are broken (not just rendered differently) are fixed too.

I can take a stab at this. I've missed certain markdown features too. 

```
$ ls -l internal/
[...]
lrwxrwxrwx 1 matt matt   18 Mar  2 06:36 Markdown.pl -> /usr/bin/cmark-gfm
-rwxr-xr-x 1 matt matt  35K Feb  4  2018 Markdown.pl.old
[...]
```

**Comment by aadibajpai** [comment]
> Adding proper support for a different markdown parser should be straight forward. As a hack I installed the Debian cmark-gfm package, symlinked to it, and rebuilt my blog. Some things rendered differently and it looks like the `{toc}` macro is broken now. But otherwise I think it would not be too hard to make configurable the path of the binary to use. Also, I am open to replacing Markdown.pl in the repo with a cmark-gfm binary as long as things that are broken (not just rendered differently) are fixed too.
> 
> I can take a stab at this. I've missed certain markdown features too.
> 
> ```
> $ ls -l internal/
> [...]
> lrwxrwxrwx 1 matt matt   18 Mar  2 06:36 Markdown.pl -> /usr/bin/cmark-gfm
> -rwxr-xr-x 1 matt matt  35K Feb  4  2018 Markdown.pl.old
> [...]
> ```

I had just edited MARKDOWN variable to the cmark-gfm binary and kept the og binary as fallback, but this is way simpler. One thing though, do the github extensions in cmark-gfm (strikethrough, autolinking etc.) work for you right off the bat?

**Comment by pastly** [comment]
No. But it looks like all that needs to happen is providing the extensions you want enabled as arguments to cmark-gfm. 

I got this :)

**Comment by pastly** [comment]
I pushed commits making the change to cmark-gfm. All extensions are specified when cmark-gfm is called, thus enabled. 

As I already mentioned, this has resulted in some bits of my blog no longer rendering correctly (note: I haven't rebuilt it on a public webserver yet).

`{toc}` is still broken. Upon switching to cmark-gfm it doesn't link to sections in the post any more.

A new major release will be made once the latter problem is fixed and another other discovered problems are fixed too.

**Comment by pastly** [comment]
`{toc}` is fixed by specifying `--unsafe` flag to `cmark-gfm`. Those rendering issues I was seeing are magically fixed now?!

Gotta write a blog post about new major release. Then will release it.

I don't intend on making any other changes before v5.0.0, so you might consider the current master branch ready for you.

I'll close this once v5.0.0 is out.

**Comment by aadibajpai** [comment]
> `{toc}` is fixed by specifying `--unsafe` flag to `cmark-gfm`. Those rendering issues I was seeing are magically fixed now?!

Hmm makes sense because I presume `{toc}` injects raw html.
> 
> Gotta write a blog post about new major release. Then will release it.
> 
> I don't intend on making any other changes before v5.0.0, so you might consider the current master branch ready for you.
> 
> I'll close this once v5.0.0 is out.

Pulled in the changes and rebuilt and pushed. Working perfectly! I'm not really using `{toc}` because of that headings error that was happening, I wonder if this fixes that too 🤔 

Thanks again for the update, much appreciated.

**Comment by pastly** [comment]
v5.0.0 is released
